adding credirects v1

diff --git a/bdocs b/bdocs
--- a/bdocs
+++ b/bdocs
@@ -6,15 +6,17 @@
 
 set -e
 
-# The project's root directory.
+# The project's root directory and redirect file.
 export PROJECT_ROOT="$(dirname "$(realpath "$0")")"
+export REDIRECT_FILE="./assets/js/broken_redirect_list.js"
 
 # All scripts exported so they can source bdocs and call each other if needed.
 export DEPLOY="$PROJECT_ROOT/scripts/create_deploy_text.sh"
 export RELEASE="$PROJECT_ROOT/scripts/create_release_text.sh"
 export TLINKS="$PROJECT_ROOT/scripts/transform_reference_links.py"
 export RLINKS="$PROJECT_ROOT/scripts/remove_unused_reference_links.rb"
-export REDIRECTS="$PROJECT_ROOT/scripts/list_redirect_urls.sh"
+export CREDIRECTS="$PROJECT_ROOT/scripts/create_redirects.sh"
+export LREDIRECTS="$PROJECT_ROOT/scripts/list_redirect_urls.sh"
 
 # Displays usage for bdocs
 display_help() {
@@ -25,22 +27,33 @@ USAGE:
   ./bdocs [option]
 
 OPTIONS:
-  deploy       Create the deploy body text for weekly deployments
-  release      Create the release body text for monthly releases
-  tlinks       Transform reference links to inline links on 1 or more pages
-  rlinks       Remove reference links that are not being used on 1 or more pages
-  redirects    List the old URLs for all new redirects in this branch
-  help         Display this help message and exit
+  deploy         Create the deploy body text for weekly deployments
+  release        Create the release body text for monthly releases
+  tlinks         Transform reference links to inline links on 1 or more pages
+  rlinks         Remove unused reference links on 1 or more pages
+  credirects     Create redirects for all changed files in _docs
+  lredirects     List the old URLs for all new redirects in this branch
+  help           Display this help message and exit
 
 EOF
 }
 
-# If a file or directory is required, check if it was passed and block if not.
+# If a file or directory is required, pass or fail.
 require_path_or_file() {
     if [[ -z "$1" ]]; then
         echo "Error: A file or directory path is required."
         exit 1
     fi    
+}
+
+# If new merges into 'develop' are required, pass or fail.
+require_new_merges() {
+    LATEST_COMMIT_HASH=$(git log --max-count=1 --format="%H" origin/master ^origin/develop)
+    COMMIT_LOGS=$(git log --first-parent "$LATEST_COMMIT_HASH"..origin/develop)
+    if [ -z "$COMMIT_LOGS" ]; then
+        echo "Error: No new merges into 'develop' since the last deployment."
+        exit 1
+    fi
 }
 
 # Check if no arguments were provided
@@ -49,9 +62,13 @@ if [[ $# -eq 0 ]]; then
     exit 1
 fi
 
+# Fetch the latest changes from the remote quietly.
+git fetch origin develop --quiet
+
 # Argument parsing
 case $1 in
     deploy)
+        require_new_merges
         if [[ $# -eq 3 ]]; then
             "$DEPLOY" "$2" "$3"
         else
@@ -59,22 +76,26 @@ case $1 in
         fi
         ;;
     release)
+        require_new_merges
         "$RELEASE"
         ;;
     tlinks)
-        require_path_or_file "$2" && "$TLINKS" "$2"
-
-        # Run rlinks next to clean up unused reference links.
-        "$RLINKS" "$2"
+        require_path_or_file "$2"
+        "$TLINKS" "$2"
+        "$RLINKS" "$2" # Run rlinks next, to clean up unused reference links.
         ;;
     rlinks)
-        require_path_or_file "$2" && "$RLINKS" "$2"
+        require_path_or_file "$2" 
+        "$RLINKS" "$2"
         ;;
-    redirects)
+    credirects)
+        "$CREDIRECTS"
+        ;;
+    lredirects)
         if [[ $# -eq 2 ]]; then
-            "$REDIRECTS" "$2"
+            "$LREDIRECTS" "$2"
         else
-            "$REDIRECTS"
+            "$LREDIRECTS"
         fi
         ;;
     help)
